version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13.10-stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: |
          sudo apt -y update
          sudo apt -y install python3 python3-venv
      - run:
          name: Beats dashboards
          command: make beats-dashboards
          environment:
            PLATFORMS: linux/amd64
      - run:
          name: Make release
          command: make release
          environment:
            PLATFORMS: linux/amd64
            BEATS: metricbeat
