version: 2.1

jobs:
  build:
    working_directory: ~/beats
    docker:
      - image: circleci/golang:1.13.10-stretch
    steps:
      - checkout:
            path: ~/beats
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          name: Update the things
          command: |
            sudo apt update -y
            sudo apt -y install python3 python3-venv
            go get -ldflags="-X github.com/magefile/mage/mage.gitTag=1.10.0" github.com/magefile/mage
      - run:
          name: Beats dashboards
          environment:
            PLATFORM: linux/amd64
          command: make beats-dashboards
      - run:
          name: Make release
          working_directory: ~/beats/metricbeat
          environment:
            PLATFORM: linux/amd64
            BEATS: metricbeat
          command: mage package
