version: 2.1

jobs:
  build:
    working_directory: ~/beats
    docker:
      - image: circleci/golang:1.13.10-stretch
    steps:
      - checkout:
            path: ~/beats
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: sudo apt -y install python3 python3-venv
      - run:
          name: Make release
          command: |
            echo 'export GOPATH=~/go' >> $BASH_ENV
            echo 'export GODEBUG=true' >> $BASH_ENV
            source $BASH_ENV
            PLATFORM=linux/amd64 BEATS=metricbeat make release
