version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13.1-stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: |
          sudo apt -y update
          sudo apt -y install python3 python3-venv
      - run:
          name: Beats dashboards
          command: make beats-dashboards
          environment:
            PLATFORMS: linux/amd64
      - run:
          name: Make release
          command: |
          environment:
            echo 'export PLATFORM=linux/amd64' >> $BASH_ENV
            echo 'export BEATS=metricbeat' >> $BASH_ENV
            source $BASH_ENV
            make release
