version: 2.1

jobs:
  build:
    docker:
      - image: circleci/golang:1.13.10-stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.06.0-ce
      - run: |
           sudo apt -y install python3 python3-venv
      - run:
          name: Make release
          command: |
             PLATFORM=linux/amd64 BEATS=metricbeat make release
